package Shapes.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Canvas = 0;
  public static final int Circle = 1;
  public static final int Color = 2;
  public static final int ColorReference = 3;
  public static final int Shape = 4;
  public static final int Square = 5;
  public static final int Triangle = 6;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xef39077f87e64503L, 0xbcbe592bc9efb948L);
    builder.put(0x37be5b6688e2093fL, Canvas);
    builder.put(0x37be5b6688e20936L, Circle);
    builder.put(0x37be5b6688e30b80L, Color);
    builder.put(0x37be5b6688e4f39aL, ColorReference);
    builder.put(0x37be5b6688e20933L, Shape);
    builder.put(0x37be5b6688e2093bL, Square);
    builder.put(0x37be5b6689059d8aL, Triangle);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
