package Shapes.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCanvas = createDescriptorForCanvas();
  /*package*/ final ConceptDescriptor myConceptCircle = createDescriptorForCircle();
  /*package*/ final ConceptDescriptor myConceptColor = createDescriptorForColor();
  /*package*/ final ConceptDescriptor myConceptColorReference = createDescriptorForColorReference();
  /*package*/ final ConceptDescriptor myConceptShape = createDescriptorForShape();
  /*package*/ final ConceptDescriptor myConceptSquare = createDescriptorForSquare();
  /*package*/ final ConceptDescriptor myConceptTriangle = createDescriptorForTriangle();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, "jetbrains.mps.execution.util");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCanvas, myConceptCircle, myConceptColor, myConceptColorReference, myConceptShape, myConceptSquare, myConceptTriangle);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Canvas:
        return myConceptCanvas;
      case LanguageConceptSwitch.Circle:
        return myConceptCircle;
      case LanguageConceptSwitch.Color:
        return myConceptColor;
      case LanguageConceptSwitch.ColorReference:
        return myConceptColorReference;
      case LanguageConceptSwitch.Shape:
        return myConceptShape;
      case LanguageConceptSwitch.Square:
        return myConceptSquare;
      case LanguageConceptSwitch.Triangle:
        return myConceptTriangle;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCanvas() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Canvas", 0xef39077f87e64503L, 0xbcbe592bc9efb948L, 0x37be5b6688e2093fL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:fee850af-a7ae-4a54-be03-af50a16f8289(Shapes.structure)/4016748413602367807");
    b.version(3);
    b.aggregate("shapes", 0x37be5b6688e20941L).target(0xef39077f87e64503L, 0xbcbe592bc9efb948L, 0x37be5b6688e20933L).optional(true).ordered(true).multiple(true).origin("4016748413602367809").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCircle() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Circle", 0xef39077f87e64503L, 0xbcbe592bc9efb948L, 0x37be5b6688e20936L);
    b.class_(false, false, false);
    // extends: Shapes.structure.Shape
    b.super_(0xef39077f87e64503L, 0xbcbe592bc9efb948L, 0x37be5b6688e20933L);
    b.origin("r:fee850af-a7ae-4a54-be03-af50a16f8289(Shapes.structure)/4016748413602367798");
    b.version(3);
    b.property("x", 0x37be5b6688e20937L).type(PrimitiveTypeId.INTEGER).origin("4016748413602367799").done();
    b.property("y", 0x37be5b6688e20938L).type(PrimitiveTypeId.INTEGER).origin("4016748413602367800").done();
    b.property("radius", 0x37be5b6688e20939L).type(PrimitiveTypeId.INTEGER).origin("4016748413602367801").done();
    b.alias("circle");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Color", 0xef39077f87e64503L, 0xbcbe592bc9efb948L, 0x37be5b6688e30b80L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:fee850af-a7ae-4a54-be03-af50a16f8289(Shapes.structure)/4016748413602433920");
    b.version(3);
    b.alias("color");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColorReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "ColorReference", 0xef39077f87e64503L, 0xbcbe592bc9efb948L, 0x37be5b6688e4f39aL);
    b.class_(false, false, false);
    b.origin("r:fee850af-a7ae-4a54-be03-af50a16f8289(Shapes.structure)/4016748413602558874");
    b.version(3);
    b.associate("target", 0x37be5b6688e4f39bL).target(0xef39077f87e64503L, 0xbcbe592bc9efb948L, 0x37be5b6688e30b80L).optional(false).origin("4016748413602558875").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForShape() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Shape", 0xef39077f87e64503L, 0xbcbe592bc9efb948L, 0x37be5b6688e20933L);
    b.class_(false, true, false);
    b.origin("r:fee850af-a7ae-4a54-be03-af50a16f8289(Shapes.structure)/4016748413602367795");
    b.version(3);
    b.aggregate("color", 0x37be5b6688e4f3a7L).target(0xef39077f87e64503L, 0xbcbe592bc9efb948L, 0x37be5b6688e4f39aL).optional(false).ordered(true).multiple(false).origin("4016748413602558887").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSquare() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Square", 0xef39077f87e64503L, 0xbcbe592bc9efb948L, 0x37be5b6688e2093bL);
    b.class_(false, false, false);
    // extends: Shapes.structure.Shape
    b.super_(0xef39077f87e64503L, 0xbcbe592bc9efb948L, 0x37be5b6688e20933L);
    b.origin("r:fee850af-a7ae-4a54-be03-af50a16f8289(Shapes.structure)/4016748413602367803");
    b.version(3);
    b.property("pointAX", 0x37be5b6688e2093cL).type(PrimitiveTypeId.INTEGER).origin("4016748413602367804").done();
    b.property("pointAY", 0x37be5b6688e2093dL).type(PrimitiveTypeId.INTEGER).origin("4016748413602367805").done();
    b.property("pointBX", 0x37be5b6688e2093eL).type(PrimitiveTypeId.INTEGER).origin("4016748413602367806").done();
    b.property("pointBY", 0x37be5b6689059f44L).type(PrimitiveTypeId.INTEGER).origin("4016748413604699972").done();
    b.property("pointCX", 0x37be5b6689059f77L).type(PrimitiveTypeId.INTEGER).origin("4016748413604700023").done();
    b.property("pointCY", 0x37be5b6689059fa0L).type(PrimitiveTypeId.INTEGER).origin("4016748413604700064").done();
    b.alias("square");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTriangle() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Triangle", 0xef39077f87e64503L, 0xbcbe592bc9efb948L, 0x37be5b6689059d8aL);
    b.class_(false, false, false);
    // extends: Shapes.structure.Shape
    b.super_(0xef39077f87e64503L, 0xbcbe592bc9efb948L, 0x37be5b6688e20933L);
    b.origin("r:fee850af-a7ae-4a54-be03-af50a16f8289(Shapes.structure)/4016748413604699530");
    b.version(3);
    b.property("pointAX", 0x37be5b6689072c6aL).type(PrimitiveTypeId.INTEGER).origin("4016748413604801642").done();
    b.property("pointAY", 0x37be5b6689072c9dL).type(PrimitiveTypeId.INTEGER).origin("4016748413604801693").done();
    b.property("pointBX", 0x37be5b6689072cbcL).type(PrimitiveTypeId.INTEGER).origin("4016748413604801724").done();
    b.property("pointBY", 0x37be5b6689072cf9L).type(PrimitiveTypeId.INTEGER).origin("4016748413604801785").done();
    b.property("pointCX", 0x37be5b6689072d22L).type(PrimitiveTypeId.INTEGER).origin("4016748413604801826").done();
    b.property("pointCY", 0x37be5b6689072d4bL).type(PrimitiveTypeId.INTEGER).origin("4016748413604801867").done();
    b.alias("triangle");
    return b.create();
  }
}
